title: "Neal Swayze - About"
author: "Neal Swayze"
description: "Neal Swayze"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "about.md", title: "About"}
  - {file: "Portfolio.md", title: "Portfolio"
  - {file: "publications.md", title: "Publications"}
  - {file: "old_index.html", title: "Posts"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:nealswayze1@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/nealswayze"}
  - {title: Subscribe, icon: rss, url: "https://twitter.com/NealSwayze?s=20"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

encoding: UTF-8
